// client/src/components/ProdItem.jsx
import React from 'react'

export default function ProdItem({prod, addToCart}) {
    return (
        <div>
            <img src={prod.img} alt="prod img" className="prod-list-img" />
            <h1>{prod.name}, ${prod.price}</h1>
            <button onClick={()=>addToCart(prod.id)} >ADD TO CART</button>
        </div>
    )
}

// Documents/OrenSayag/lesson41/client/src/app/components/prod-item/prod-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import ProdModel from 'src/app/models/prod.model';
import { DataService } from 'src/app/services/data.service';

@Component({
  selector: 'app-prod-item',
  templateUrl: './prod-item.component.html',
  styleUrls: ['./prod-item.component.css']
})
export class ProdItemComponent implements OnInit {

  @Input()
  prod:ProdModel

  constructor(
    public _data:DataService
  ) { }

  ngOnInit(): void {

  }

}

<div class="prod-item">
  <h2>{{ prod.name }}</h2>
  <h1>${{ prod.price }}</h1>
  <img [src]="prod.img">
  <button (click)="_data.addToCart(prod.id)">Add to Cart</button>
</div>
