// client/src/app/components/cart-item/cart-item.component.ts
import { Component, Input, OnInit } from '@angular/core';
import ProdModel from 'src/app/models/prod.model';
import { DataService } from 'src/app/services/data.service';

@Component({
  selector: 'app-cart-item',
  templateUrl: './cart-item.component.html',
  styleUrls: ['./cart-item.component.css']
})
export class CartItemComponent implements OnInit {


@Input()
public cart:ProdModel;


  constructor(
    public _data:DataService
  ) { }

  ngOnInit(): void {
  }

}

<div class="cart-item">
  <img [src]="cart.img" alt="cart img">
  <div class="info">
    <h1>{{ cart.name }}</h1>
    <h2>${{ cart.price }}</h2>
  </div>
  <button (click)="_data.delFromCart(cart.id)"> X </button>
</div>

// client/src/components/CartItem.jsx
import React from 'react'

export default function CartItem({item, delFromCart}) {
    return (
        <div className="cart-list-item">
            <img src={item.img} alt="img" />
            <div className="info">
                <h3>{item.name}</h3>
                <h2>{item.price}</h2>
                <button onClick={()=>delFromCart(item.id)} >DELETE</button>
            </div>
        </div>
    )
}
